version: '3.8'

services:
  trading-agent:
    build: .
    container_name: ada-analytics-trading-agent
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - TZ=America/New_York
    env_file:
      - .env
    volumes:
      - ./agent_state.json:/app/agent_state.json
      - ./logs:/app/logs
    networks:
      - trading-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  trading-network:
    driver: bridge

volumes:
  agent_data:
    driver: local