[build]
builder = "nixpacks"
buildCommand = "deno cache --reload main_new.ts"

[deploy]
startCommand = "deno run --allow-all main_new.ts"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "always"