[build]
builder = "nixpacks"
buildCommand = "deno cache main_new.ts"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "always"
restartPolicyMaxRetries = 3
startCommand = "deno run --allow-all --no-check main_new.ts"