[build]
builder = "nixpacks"

[deploy]
startCommand = "deno run --allow-all main.ts --transport http --host 0.0.0.0 --port 8000"
healthcheckPath = "/health"
healthcheckTimeout = 300

[env]
QUIVER_API_TOKEN = ""

[[services]]
name = "quiver-mcp-server"

[services.source]
repo = "your-username/ada-analytics"
rootDirectory = "Ada-Analytics/quiver-mcp-server"

[services.variables]
NODE_ENV = "production"
TZ = "America/New_York"
PORT = "8081"

[services.healthcheck]
path = "/health"
interval = 30
timeout = 10
retries = 3

[services.resources]
memory = 256
cpu = 250

[services.serverless]
enabled = true 